services:
    debug-db:
        build:
            args:
                POSTGRES_DB: $PSQL_DB
                POSTGRES_USER: $PSQL_USER
                POSTGRES_PASSWORD: $PSQL_PASSWORD
        container_name: "${CONTAINER_NAME}"
        volumes:
            - ./postgres:/usr/src/postgres
        ports:
            - "${PSQL_PORT}:5432"